[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fauxlogger"
version = "0.1.7"

[tool.pytest.ini_options]
addopts = "-s"

[project.optional-dependencies]
test = [
    "pytest>=9.0",
]